### ISSUE TITLE
Discussion: Support for generic 'cube rail' games

### ISSUE THREAD

**Issue by shazzner** [18xx-maker/18xx-maker#15]
Hi there, so I've been using this app to help prototype some of my 18xx designs, though recently I've had ideas for more generic 'cube rail' games, ie. Irish Gauge or Chicago Express.

It could be done currently but the sizing for the hexes are designed for 18xx tiles instead of singular cubes, it might also necessitate generic markets and some board references.

Support for this though, might be beyond the scope of this project however so the purpose of this issue is to see if there is some interest and if so, how one might go about implementing it.

**Comment by kelsin** [comment]
Definitely in scope. What would you say the list of things / changes that you would need are?

There is already a component for a cube square in the code, so this is mainly just other things to put near the board?

**Comment by shazzner** [comment]
Awesome, so the main things, in my opinion, are:
- Possibly, some sort of flag that denotes the data is in '18xx' or 'cube' mode
- Adjustable hex size, this could possibly be already implemented
- Standard API for arbitrary board decorations to add text, charts, cube tracks etc

**Comment by kelsin** [comment]
What would setting 18xx or Cube mode change?

**Comment by shazzner** [comment]
Good question, and the more I think about it the more I'm not so sure it's needed, if there is a setting to adjust the base hex diameter, then that can just be incorporated into the json data. Presumably if there is no data for trains or charters, the user won't be presented with an option to view them.

**Comment by kelsin** [comment]
So based on this I'm going to make this the todo item for this issue:

- [ ] Support for generic SVG's added to maps
- [ ] Support for generic tables added to maps
- [ ] Test support for hex size definition and add this (properly) to the `config.json` file and schema
- [ ] Clean up what happens when you don't define data for markets, privates, companies, trains etc.

**Comment by kelsin** [comment]
Example of table that I can use to implement generic tables: https://boardgamegeek.com/image/306570/1848-australia
