### ISSUE TITLE
company names ignoring "rotation"

### ISSUE THREAD

**Issue by th3tick** [18xx-maker/18xx-maker#171]
Adding "rotation" to this section netted no actual city name rotation:

      "cities": [
        {
          "size": 3,
          "companies": [
            {
              "rotation": 30,
              "label": "MKHL"
            },
            {
              "rotation": 30,
              "label": "BA"
            },
            {
              "rotation": 30,
              "label": "Th"
            }
          ]
        }
      ],

**Comment by kelsin** [comment]
Adding this in, but it might cause some issues. Will just have to see if it breaks many games.

**Comment by kelsin** [comment]
Right now I still have city's not providing their rotation context to names, but we can figure that out later. I did make name aware of it, but still not passing it.
