### ISSUE TITLE
need icons for train, pullman, city/token, and tunnel

### ISSUE THREAD

**Issue by th3tick** [18xx-maker/18xx-maker#176]
would be handy...

**Comment by kelsin** [comment]
Any ideas for any of these? References? I don't mind doing the svg work to code them up, but want to make sure it's what people want :)

**Comment by th3tick** [comment]
I've yet too find anything perfect, but this is the one that got me started:
https://en.wikipedia.org/wiki/File:Tunnel_only.svg
I'm mostly thinking it would be nice to have icons for most all of the common private powers.  A steam engine is possible, a pullman... difficult.  As for the station token, one matching a specified color that looks like a 3D cylinder would be great - e.g.:
https://svg-clipart.com/red/I9Q3Fdo-router-3d-red-down-grad-clipart

**Comment by knauman** [comment]
18C2C needs a few: a tree, fish, coal, coin, US Army Corps, builder, crane, and a golden spike.
![token labels](https://user-images.githubusercontent.com/51214001/73844047-68d39100-47e5-11ea-8147-7e2b23d55b42.png)

**Comment by kelsin** [comment]
Train icon added.

**Comment by kelsin** [comment]
Closing since this has been open for a long time. Lots of icons added and other SVG's can be added easily as well. Open a new issue once we know of an icon you want.
