### ISSUE TITLE
Images for train cards

### ISSUE THREAD

**Issue by shazzner** [18xx-maker/18xx-maker#21]
As I mentioned on the 18xx slack, I added a small train image to the card. It was a small svg, CC licensed, I just found online. I'm not super in love with my bottom-left positioning, most 18xx games with images usually center them and include some small description.

The way I was doing it won't work well with the data file (I was importing it directly in the jsx), so this issue is to kind of come up with the best way to implement it in the json data.

Ideas:
Each train type will have an `image:` key, that contains and object with some data on the image and position. Perhaps something like this:
```
image: [
  {
    src: "*http link*", // will this create problems offline?
    anchor: "center", // "bottom-left", "center", "left"...
    text: {
     name: "Baldwin (4-4-0}",
     // font: ?
     align: "center"
    },
    width: 1.25, // in inches or some other unit
    height: "auto", // scales in proportion to the width
    // license: ?
  }
]
```

Perhaps it can also support embedded svg vector data.

Thoughts?

**Comment by shazzner** [comment]
I think might _have_ to support svg data, as external links could be lost. The alternative is to put raw raster image data in there, which could get messy very quickly.

**Comment by kelsin** [comment]
For now I think we just add it the image once in App.jsx: https://github.com/kelsin/18xx/blob/master/src/App.jsx#L79

Then we just can provide an option for all games on whether to add the image or not to trains. Better than nothing and we can improve later?

**Comment by kelsin** [comment]
Images added that Josh Star found for me. We can add new train images anytime. I'm ok with train images being bitmaps. If you have other images you would like to add, please open a new issue @shazzner (and sorry for the annoyance). We'll get any you want added!

**Comment by shazzner** [comment]
Sounds good, thanks @kelsin !
