### ISSUE TITLE
Need Icon for Gold and Cattle

### ISSUE THREAD

**Issue by ngeunit1** [18xx-maker/18xx-maker#213]
For use in 18C2C. See example in image on BGG https://boardgamegeek.com/image/1249685/18c2c-manifest-destiny.

Just using a proxy for now.

**Comment by kelsin** [comment]
Does the meat icon not work for cattle?

**Comment by kelsin** [comment]
Would the "token" icon with yellow or gold as a color work for gold? If not what would we want the gold icon to be?

**Comment by kelsin** [comment]
With proper coloring the `token` and `cylinder` icons could be used for gold. `meat` is already there for cattle.
