### ISSUE TITLE
Changing tile width affects the page size for map-paginated view

### ISSUE THREAD

**Issue by Xenir** [18xx-maker/18xx-maker#217]
Looks like the size of the map-paginated view is calculated based on the "Tiles - Tile Width" instead of "Tiles - Map Tile Width". If the tile width is set to a smaller value (e.g. 95% of the map tile size), the resulting pagination cuts off the bottom and the right side of the map:
![image](https://user-images.githubusercontent.com/1089971/75764852-cb657180-5d3e-11ea-8652-1c5e35974c8e.png)
Tile width set to a much bigger value (e.g. 130% of the map tile size) => a lot of empty space below/on the right side:
![image](https://user-images.githubusercontent.com/1089971/75765308-97d71700-5d3f-11ea-93e5-5badfc7d2291.png)

**Comment by Xenir** [comment]
I have created a pull request for that fix: #218

**Comment by kelsin** [comment]
Reopen if there was something else that your PR didn't catch!
