### ISSUE TITLE
Stock Market

### ISSUE THREAD

**Issue by kelsin** [18xx-maker/18xx-maker#22]
Have a set size for stock market squares (probably start with JCL's size for 1828). Paginate when needed, and center otherwise with cut lines.

**Comment by kelsin** [comment]
As part of this we're going to move to CSS grid layouts and be making sure that all par elements fit on the page without overlap.

We will also be automatically choosing portrait or landscape based on number of pages needed to print with the chosen page size.

**Comment by wcraigtrader** [comment]
The 1-dimensional markets (1846, 1867) also need a lot of work. In particular, the market for 1867 has multiple bands for different types of companies (minor, major aka stock), as follows:

| Range | Color | Meaning |
|:---:|:---:|:--- |
| 35-45 | White | |
| 50-65 | Brown | Only Minor Companies may start here |
| 70-135 | Red | Any company may start here |
| 100-165 | Yellow | Minor companies may convert here |
| 150-200 | Purple | Only Stock Companies may start here |
| 220-540 | White | |

Also, Minor Companies can't advance beyond $165/share.

**Comment by kelsin** [comment]
This should largely be done, if there are new requests, we can open new issues.
