### ISSUE TITLE
icons/logos with colored backgrounds make for weird tokens

### ISSUE THREAD

**Issue by th3tick** [18xx-maker/18xx-maker#254]
This token's svg is square, and is fully blue on the top half:
<img width="62" alt="Screen Shot 2020-04-04 at 3 37 17 PM" src="https://user-images.githubusercontent.com/48138042/78461925-5c0ad680-768a-11ea-832f-3c10e94adb24.png">

Ones with a fully-colored background show a full square.

**Comment by kelsin** [comment]
We shouldn't have SVG logos that look like this in the repo. Editing colors is one thing, but we're not going to write code that is able to recognize shapes inside of SVG's and edit them. That's way beyond the scope of this project.
