### ISSUE TITLE
adding anything to 1D market gets chopped off in "yarn print"

### ISSUE THREAD

**Issue by th3tick** [18xx-maker/18xx-maker#278]
In some of the games where there's a legend at the bottom of the market, it's chopped off:

<img width="964" alt="Screen Shot 2020-04-17 at 11 05 29 PM" src="https://user-images.githubusercontent.com/48138042/79628644-0578b000-8100-11ea-81c8-9b17905e4431.png">

That can be resolved by tucking it tighter here:

    transform={`translate(${current} ${1 * data.height + (data.stock.title === false ? 25 : 75)})`}

in market/Market.jsx by changing the 75 to 60, but it exposes an overall problem.  Once I tried adding a roundTracker to it, there's no way to get it to fit onto the page.  It's always chopped off unless you put it over some other element, making it impossible to use.  There also doesn't appear to be a way to expand the canvas you're working with to make room for it.

On 1.5/2D markets. there are ways to make room.  On 1D markets, there is not, making it have to all be done in post-processing.

**Comment by th3tick** [comment]
Note that the chopping is really only visible in "yarn print" results.  On the screen it looks fine, but the PDF it generates is chopped.

**Comment by kelsin** [comment]
This appears fixed. `pnpm print 1867` works for me now. So... yay old bugs dissapearing.
