### ISSUE TITLE
small die tiles paper width needs to be configurable

### ISSUE THREAD

**Issue by th3tick** [18xx-maker/18xx-maker#326]
The current value in src/tilesheet.util.js:
c.pageWidth = 800;

cuts off the bleeds a the side of the sheet.  This can lead to small die alignment issues creating a strip of white dots down the sides of the resulting cut tiles.

Many printers can print past that 0.25" margin, so it should be a config option to allow for it.  0.1" on either side totally eliminates the problem.

It would be worthwhile to set directly rather than requiring the user to know how much more is needed, adjust it to 820, then have to fix the margins to 15 to match.

**Comment by kelsin** [comment]
We should set it to whatever the die needs to be full (so event 0 etc). Then make sure the display of the page is still centered and uses the config for paper margin set by the user to properly print.

**Comment by kelsin** [comment]
This feels like it deals with the configurability settings of dies, which I want to look into later.
