### ISSUE TITLE
with a narrow browser, the drop area for jsons is too large

### ISSUE THREAD

**Issue by th3tick** [18xx-maker/18xx-maker#329]
It (and other bits) is taking up a lot of space:
<img width="1434" alt="Screen Shot 2020-06-23 at 11 21 42 AM" src="https://user-images.githubusercontent.com/48138042/85434730-b9a11780-b543-11ea-80f5-92ad11af58ac.png">
which results in an annoying scrollbar on the right.  I would expect it to self-adjust better so that the scrollbar is unneeded in most cases.

Fundamentally, that scrollbar's interaction with the one for the game list is annoying.

**Comment by kelsin** [comment]
Drop area is now the full app/website, all the time, on any page.
