### ISSUE TITLE
when changing a game title, it would be nice if the list of games dynamically updated, too

### ISSUE THREAD

**Issue by th3tick** [18xx-maker/18xx-maker#330]
While I realize finding new games isn't something it can do dynamically, but given that it can notice updates in game files and reload the resulting pages, having the list of games update the game names as well would be handy.

I noticed this when cloning a game and trying to get it to show up as a different game.  The only way I could get that noticed was restarting everything.

**Comment by kelsin** [comment]
This should work better now and will be greatly improved soon when I add the ability to add folders of assets that the app/site remember.
