### ISSUE TITLE
"Cards" is available as an option even when the game has none

### ISSUE THREAD

**Issue by th3tick** [18xx-maker/18xx-maker#332]

**Comment by th3tick** [comment]
same for Charters, and it crashes (relatively speaking) if you click on it

**Comment by kelsin** [comment]
Charters should be only available if a game file has a `company` field: https://github.com/18xx-maker/18xx-maker/blob/master/src/nav/GameNav.jsx#L191

Do you have an example game where there's something else I should be checking for for charters?

For cards one of the ideas is that player cards should always be available, but if you don't have a players object that doesn't make sense of course. I want to abstract some of that utility to determine what a game has and stick it in the @18xx-maker/games project and then reference it in here. Will do that as part of solving this.

**Comment by th3tick** [comment]
I have a "tiles only" game.  I'm guessing the problem is you have no idea how many player cards to generate if you have no player count.

**Comment by th3tick** [comment]
Tokens do this too if you have companies, but no tokens in any of them.

**Comment by th3tick** [comment]
This game isn't quite tiles-only, but its companies are just there so that I can use them on tiles.  Therefore, they have no shares or tokens defined.  I think looking for companies is insufficient, but need to know whether any of those companies have shares or tokens.  Otherwise the choice is there, but all it does is crashes.

**Comment by kelsin** [comment]
Will fix more soon once I redo the UI.
