### ISSUE TITLE
app version generates error pages for empty charters and tokens

### ISSUE THREAD

**Issue by th3tick** [18xx-maker/18xx-maker#334]
This is a file it generated
[1852-charters.pdf](https://github.com/18xx-maker/18xx-maker/files/4826934/1852-charters.pdf)

same error as seen in the web version, but more than disabling those entries in the list, the "export" needs to handle this better, and probably so does Charters.jsx for empty token arrays.

**Comment by kelsin** [comment]
Probably too old to duplicate but if you see this again I'd love to fix.
