### ISSUE TITLE
App (beta 14): PNGs not exporting and exported PDFs only show the "load games" screen.

### ISSUE THREAD

**Issue by goldencow2** [18xx-maker/18xx-maker#343]
I feel like this must be my own error as files for some other games export fine.

[1865-cards.pdf](https://github.com/18xx-maker/18xx-maker/files/4872087/1865-cards.pdf)
Game: https://drive.google.com/file/d/1yL_R8YZHo727yUeItaTryHIc5aNqMPbb/view?usp=sharing
Config: https://drive.google.com/file/d/1Zzobqvt2JHFmqcTeqQdsKKdVV0griQ2B/view?usp=sharing

**Comment by bjstover** [comment]
I am having the same issue with a game I am messing around with making. A friend was able to "print" on his computer, but I get the same loading games screen.

**Comment by kelsin** [comment]
This shouldn't happen in the latest app, but please let me know if so.
