### ISSUE TITLE
dtgDie card layout needs cut lines

### ISSUE THREAD

**Issue by th3tick** [18xx-maker/18xx-maker#345]
The dtgDie layout is the most condensed card layout.  However, if you don't have a die cutter, there is no way to use this layout.

**Comment by th3tick** [comment]
Put another way, I'd like to start wasting less paper and lamination.

**Comment by ventusignis** [comment]
@th3tick the DTG die uses custom (smaller) card sizes. Have you considered altering the config to shrink the cards down somewhat and using the free layout? You can also zero out the bleed and shrink the cut line size to fit more cards on the page too.

**Comment by kelsin** [comment]
Yes should be able to recreate this with card options and the free layout at the moment. Since we have another issue open to deal with adding settings to different dies, going to close this one out.
