### ISSUE TITLE
bottom horizontal scrollbar in map occludes hex legend

### ISSUE THREAD

**Issue by th3tick** [18xx-maker/18xx-maker#347]
<img width="195" alt="Screen Shot 2020-07-13 at 7 40 09 PM" src="https://user-images.githubusercontent.com/48138042/87370609-ada3e680-c540-11ea-9496-2507fd59d3f3.png">

**Comment by kelsin** [comment]
Is this when printing or in the browser? If so what browser and what map were you on so I can duplicate?
