### ISSUE TITLE
need way to put icons on map/hexes without big white circle

### ISSUE THREAD

**Issue by th3tick** [18xx-maker/18xx-maker#348]
The big white circle behind icons is really confusing as it looks just like a weird city.  There should be a way to just put the icon on the map without the circle.

**Comment by ventusignis** [comment]
Try putting the icon as terrain

**Comment by th3tick** [comment]
That does work.  Interestingly, it leaves room for the "cost", putting the icon off-center.  But I guess that's a different bug.

**Comment by kelsin** [comment]
Yeah we need to clean up how icons work. I def want the ability to icon without a citcle. We'll leave this open for that.

**Comment by th3tick** [comment]
fixed this at some point
