### ISSUE TITLE
18xx-maker generates blank markets

### ISSUE THREAD

**Issue by Xenir** [18xx-maker/18xx-maker#350]
For some games (e.g. [1830](https://www.18xx-maker.com/games/1830/market)) the market generated by the tool is blank (both in the browser and in the generated PDF print files) when the `Display Market Legend` is switched to off. This issue exists even in games that have no market legend (e.g. [Harzbahn](https://www.18xx-maker.com/games/Harzbahn/market)).

For other games (e.g. [1836jr](https://www.18xx-maker.com/games/1836jr-30/market) - both versions), the market is blank regardless of the state of the abovementioned setting.

This issue exists both locally and while using [https://www.18xx-maker.com/](https://www.18xx-maker.com/)
Tested on Chrome, Firefox and Edge

**Comment by kelsin** [comment]
Nice find!

**Comment by tazerface1** [comment]
I don't know if this helps, but I have the same error.  I have yet to find a title which actually generates a market.

**Comment by kelsin** [comment]
Have some fixes coming in for weird markets and par settings, but I can't duplicate this original issue anymore.
