### ISSUE TITLE
Tiles export at wrong start position when using yarn b18

### ISSUE THREAD

**Issue by philcampeau** [18xx-maker/18xx-maker#352]
Currently, when the yarn b18 command is used, tiles seem to come out offset from where they should be.

See tile trays in gamebox here: https://b17.kanga.nu/board18Map.php?dogame=532

I've tinkered around with the settings, and it seems if you set the json in the b18output to have these settings, the tiles position correctly:

      "xStart": 24,
      "yStart": 24,

**Comment by th3tick** [comment]
cause not investigated, but fixed by 09f76106b958eeac91b5132a6a710b5e8e912d43
