### ISSUE TITLE
App (v 14) not printing pdf's

### ISSUE THREAD

**Issue by bjstover** [18xx-maker/18xx-maker#353]
I'm getting an issue when trying to print my json file with the app. It creates the files but every file looks like the one attached (just a one page pdf of the "load game" screen. 

[18test-map.pdf](https://github.com/18xx-maker/18xx-maker/files/5035372/18test-map.pdf)

**Comment by kelsin** [comment]
It looks like this is when using a loaded json file that's not included in the built in games. Will try to figure this out soon.

**Comment by kelsin** [comment]
I can duplicate... it just works often for me since I have a large folder of games, have to make sure I load a json that doesn't exist on the file system while developing. Sorry for the bug, don't know how to fix it yet but will attempt some stuff asap.

**Comment by bjstover** [comment]
Thanks a bunch, I will await a fix.

**Comment by kelsin** [comment]
Please try again on beta 15. I made the game loaded not just be session based which solved the bug but might expose other bugs around restarting the app and still having your game file loaded from before... might be wanted? Don't know. we'll see!

**Comment by bjstover** [comment]
Everything works now but the map. I can export/print the map on it's own, and it is fine, but when I do the bulk export/print (whole game option) it creates a map file that is only 1KB (should be bigger). Everything else works with the bulk print. I am able to print the map on its own with the "export this component" option

**Comment by kelsin** [comment]
I had that happen to me on some games, let me lengthen the timeout to let the page render. Is this a particularly large map at all? I was worried that the random times I used were only going to be good for my machine.

**Comment by bjstover** [comment]
The map is large, yes. It goes to N/25

**Comment by kelsin** [comment]
Try the big map on Version 16 just to see if that helps?

**Comment by bjstover** [comment]
Looks like it works now, thanks.
