### ISSUE TITLE
App (v16) printing scrollbars on token pages and tile manifests.

### ISSUE THREAD

**Issue by goldencow2** [18xx-maker/18xx-maker#357]
See picture; happened with 1830 and two other games.

![scrollbar](https://user-images.githubusercontent.com/43799724/89944266-213f1f00-dbe5-11ea-8dc9-bebe620e3b2b.jpg)

**Comment by kelsin** [comment]
Is this version 16 of the app on Windows?

**Comment by goldencow2** [comment]
Yes.

**Comment by kelsin** [comment]
Fixed in #624
