### ISSUE TITLE
Tile with Slashes in Database

### ISSUE THREAD

**Issue by knauman** [18xx-maker/18xx-maker#378]
Tiles with slashes do not appear in the Tile Database, but are shown in Tiles and Manifest of a game.
![Screenshot 2020-09-20 193722](https://user-images.githubusercontent.com/51214001/93724860-cd770c80-fb78-11ea-8d2b-ad47fe4726dd.png)
![image](https://user-images.githubusercontent.com/51214001/93724880-ed0e3500-fb78-11ea-83b8-0d030fc25a81.png)

**Comment by knauman** [comment]
I have it defined in the brown tiles.
![image](https://user-images.githubusercontent.com/51214001/93724908-1333d500-fb79-11ea-83bd-8e6818721cb4.png)

**Comment by knauman** [comment]
![image](https://user-images.githubusercontent.com/51214001/93724925-3199d080-fb79-11ea-954a-02aa7d7dbe64.png)

**Comment by th3tick** [comment]
do you mean the slash in the "values"?

**Comment by kelsin** [comment]
Values are now split by any non-digit characters, and the resulting digit values are used to compare. 221 now shows up as long as 50 **_or_** 60 is in the revenue filter.
