### ISSUE TITLE
Label text for shield-style tokens is black/white according to the token's color field and not the shield's color field.

### ISSUE THREAD

**Issue by goldencow2** [18xx-maker/18xx-maker#388]
![Untitled](https://user-images.githubusercontent.com/43799724/94830161-e7162080-03d0-11eb-9ba2-2787b440c427.png)
See picture. The "LYR" text should be black on white but because the token is defined to be blue 18xx maker makes it white on white instead.

```json
    {
      "name": "Lancashire & Yorkshire Railway",
      "abbrev": "LYR",
      "color": "blue",
      "tokenType": "default",
      "token": {
        "shield": true,
        "shieldTop": "gray",
        "fontSize": 16
      },
      "shareType": "default"
    },
```

**Comment by kelsin** [comment]
I copied your definition into the latest site and it looks good. Let me know if I missed something.
