### ISSUE TITLE
move die cutter pin location and diameter to config

### ISSUE THREAD

**Issue by th3tick** [18xx-maker/18xx-maker#423]
My die pin locations are about 3/32" higher than what the tool currently generates.  I can adjust this in src/cards/index.jsx by editing the pins section, but these would be better stored in the config with the numbers in index.jsx as the defaults.

It might also be a good idea to have separate ones for cards, tiles, small tiles, and charters.  That way, a user can adjust them to whatever individual quirks of the physical dies they have.

**Comment by kelsin** [comment]
Implemented as separate pin options for cards / charters and tiles. I know that doesn't solve the two tile dies being different. I will work on an improvement to that in the future.
