### ISSUE TITLE
Tasmania Tile Number 241

### ISSUE THREAD

**Issue by joeyd4329** [18xx-maker/18xx-maker#450]
When I enter tile # 241 to be displayed via json file, it comes up as a blank tile instead of the blue Tasmania tile.

If I enter tile # 240 in the json code, I get the grey K tile correctly.

I notice that tile # 241 is in the source code under the tiles/other.json file, so I feel like there's perhaps a bug.

Am I missing something for the blue Tasmania tiles? Or is there perhaps something awry with it?

**Comment by kelsin** [comment]
Looks like the tiles weren't loading anything from that other.json tile file. Attempting a fix in [f3671fcf820f96e3896a311363ddc4bc8e21bee3](https://github.com/18xx-maker/18xx-maker/commit/f3671fcf820f96e3896a311363ddc4bc8e21bee3)

**Comment by kelsin** [comment]
Ok looks like my attempted fix (without a dev computer to check it) worked! Hopefully I didn't break anything else but closing this for now. Thanks for finding it!

**Comment by kelsin** [comment]
(Fix is in `main`, will be in the next app release once I get around to fixing some other bugs too)
