### ISSUE TITLE
Eastern half of map is missing

### ISSUE THREAD

**Issue by Vanagononaut** [18xx-maker/18xx-maker#482]
The eastern half of the map seems to be absent. 
[1871 Board.pdf](https://github.com/18xx-maker/18xx-maker/files/14606834/1871.Board.pdf)

**Comment by kelsin** [comment]
It looks like you're printing the full version of the map and letting your OS do the pagination. If you do that you're on your own. The default (for most printers and browsers) is to paginate in one direction and leave off the rest (which is what's happening here). If you want to make one GIANT pdf you need to set your page size to the proper dimensions (trial and error) before you print to PDF.

If you want to print the paginated map you should go to the paginated page: https://www.18xx-maker.com/games/TheOldPrince1871/map?paginated=true (click the paginated option in the left bar to get there) and print that. You can change paper settings in options. This will print pages with cutlines and overlap to minimize errors when putting the pages together again.
