### ISSUE TITLE
Windows update didn't work and I can't install the new version

### ISSUE THREAD

**Issue by slapphappyjazz** [18xx-maker/18xx-maker#484]
Please pardon my ignorance...

I've been running 18xx-maker on my local Windows PC for a while.  The recent release seems to have removed the version I had installed, without installing the new version.

I've tried downloading 18xx-maker-setup-1.0.0-beta-46.exe and running it by hand, but the installer pops up a message saying that Windows can't find 18xx maker.exe and asking me to locate it, which I can't do because the file no longer exists.

I've tried running the uninstall option and restarting Windows, but that didn't help.

How am I meant to install the new release?

**Comment by kelsin** [comment]
Looks like there is a bug in electron builder. Going to try a different version to see if it works.

https://github.com/electron-userland/electron-builder/issues/5461

**Comment by kelsin** [comment]
Latest version on our version of node still doesn't work. I'll try to update node / react / electron-builder ASAP to see if latest versions work but I don't know if I'll get to that today or not.

**Comment by kelsin** [comment]
Attempting a node and react-scripts update: https://github.com/18xx-maker/18xx-maker/pull/485

**Comment by kelsin** [comment]
Have it passing tests but some images on the site are broken. I will be fixing those later and then we'll get this out to see if it fixes the windows install.

**Comment by kelsin** [comment]
Publishing a test with a much newer version of stuff that works on the latest node, we'll see if the windows build works.

**Comment by kelsin** [comment]
Windows build still doesn't work, have to try more stuff later.

**Comment by kelsin** [comment]
omg I think I solved it by building for windows ia32... please check beta 53

**Comment by slapphappyjazz** [comment]
That works!  Thanks.
