### ISSUE TITLE
System18 - add new logo

### ISSUE THREAD

**Issue by ianwilson156** [18xx-maker/18xx-maker#489]
I've designed a new System18 map (Britain) which needs a sixth company. I've agreed with Scott to call it  "Pegasus", and he's come up with a design of the logo:
![PGS](https://github.com/user-attachments/assets/71f32461-cf1b-48dc-952e-607bc6185ea8)

Can we get that added to the logos please? 
I suggest we call it "System18/PGS"

**Comment by kelsin** [comment]
Sorry this has taken so long to add, I will be trying to get to it tomorrow. Just wanted to ping that I saw this a few weeks ago and just need to get the dev env setup again.

**Comment by kelsin** [comment]
https://github.com/18xx-maker/18xx-maker/pull/490

**Comment by ianwilson156** [comment]
Great, thanks!
