### ISSUE TITLE
Adding a white border to dtgDie

### ISSUE THREAD

**Issue by joeyd4329** [18xx-maker/18xx-maker#527]
I was wondering if it was possible to add the following line of code to the dtgDie card setting so it has a small 4px white border around the cards. This would allow me to use my die cutter without other cards bleeding into another.

I'm not very fluent in how to navigate and use github, but I'm 95% sure that the location of the code is in the path src/cards/card.scss and adding a line after line 8 so that the dtgDie section reads...

.cards--dtgDie {
     padding: 0.25in 0;
     border: 4px solid white;
}

I'm open to having the border adjustable by using the config, but having the default of 4px would be very helpful and would make the dtgDie usable.

Another request I have is being able to shift the die registers by the pixel but I'm not super concerned about that yet.

Thanks for considering.
![whiteBorderDtgDie](https://github.com/user-attachments/assets/91e4dc9c-4567-4e9c-b7aa-34218d5a4bdf)

**Comment by kelsin** [comment]
That seems to be a very weird fix for this. On the first page that makes ALL cards 4px closer to the registration holes AND 4px lower on the page, but on every other page of the print it ONLY makes them 4px closer to the registration holes.

Is that the goal? Are the registration holes in the wrong position for you? It was already requested that I setup options for where to place the registration holes. That seems to be the proper fix here?

**Comment by joeyd4329** [comment]
I'm actually not trying to move the cards but rather surround all the cards with a white border. Another way would be to have the border size in the configuration page be usable when the dtgDie setting is selected (right now when on the dtgDie setting, adding a value to the border doesn't do anything, also I'm hoping the border to be white).

If this suggestion actually moves all cards 4 px closer and 4px lower that's not exactly what I'm looking for. Apologies. Only looking for a white border made around each card if the dtgDie setting is selected.

**Comment by kelsin** [comment]
You want the border around each card? Is the problem that your die isn't able to be lined up properly and you get bleed when you cut?

**Comment by kelsin** [comment]
Added in main as `cards.dtgPadding`, will be in the app soon.
