### ISSUE TITLE
Home Stations for TOP

### ISSUE THREAD

**Issue by joeyd4329** [18xx-maker/18xx-maker#528]
It appears that the home stations are not being rendered on the map. The only one that seems to be there is Charlottetown, but even that is completely blacked out on the map.

![image](https://github.com/user-attachments/assets/b72e7560-b7f4-4dfd-b5b1-f86ccb1ebf61)

![image](https://github.com/user-attachments/assets/4c2f3141-f846-4877-a2cd-769c36006d7f)

Pretty sure it happened recently. It is this way on the browser and the app version I can launch from my laptop.

**Comment by kelsin** [comment]
Pushing a new version with the fix now. Thanks for finding this.

**Comment by kelsin** [comment]
Web fixed and beta 78 of the app will include this fix.
