### ISSUE TITLE
Cannot load games from PC using app

### ISSUE THREAD

**Issue by ianwilson156** [18xx-maker/18xx-maker#543]
I've just installed the latest version (beta.80) and now I can't load my games from my computer - I just get a message - "Electron game C was not found or is not a valid 18xx-maker file". I can still load the bundled games.

I can load them into the web version ok, it's just the app which doesn't work.

**Comment by kelsin** [comment]
Can you try with beta 83?

https://github.com/18xx-maker/18xx-maker/releases/tag/v1.0.0-beta.83

**Comment by ianwilson156** [comment]
I've installed the latest version (beta.88) and it's still giving the same problem.

**Comment by kelsin** [comment]
Are you on Windows? I haven't tested on windows recently. Tomorrow I will install the app and see if I can find the problem. My guess is that the new code doesn't handle windows paths. Can you go to the View menu in the app and select "App Info" and then confirm what windows version you're on?

**Comment by kelsin** [comment]
Do you get the same error with the `C` in it for any file?

**Comment by kelsin** [comment]
Ok yeah, I will install on my windows machine tomorrow and get this solved. Sorry about the breakage! I need to figure out proper testing for the app. Adding it to the TODO list.

**Comment by kelsin** [comment]
Ok beta 95 is releasing now with a fix. Please confirm later that you see it working. I've tested locally.

**Comment by kelsin** [comment]
Ok beta 96 is releasing soon and will auto clean up those broken links and remove games that were in this state. It should work better from now on.

**Comment by kelsin** [comment]
Ok it all works for me now on my windows PC. I'm going to assume you're good once you're on beta 96. Sorry for the problems.

**Comment by ianwilson156** [comment]
That works ok now, thanks for your quick solution!
