### ISSUE TITLE
1858 version bundled with the program is incomplete

### ISSUE THREAD

**Issue by ianwilson156** [18xx-maker/18xx-maker#588]
I've done my own version of 1858, which is complete. I suggest you replace the existing file.

You can get my version from here:
https://drive.google.com/drive/folders/1gisQWxtxI5aToyZQg3p8_REfVsG8dCcA
It's called 1858IDW to distinguish it from the incomplete version.

**Comment by ianwilson156** [comment]
Given the old file is unplayable, that sounds like the sensible thing to do.

**Comment by kelsin** [comment]
Updating in #592

**Comment by kelsin** [comment]
Released in beta 96.

**Comment by kelsin** [comment]
Thanks so much for updating this!
