### ISSUE TITLE
GTG blurb should be updated to reflect release of Shikoku 1889.

### ISSUE THREAD

**Issue by waymost** [18xx-maker/18xx-maker#596]
Currently the GTG blurb on the home page reads:

> [Grand Trunk Games](https://www.grandtrunkgames.com/) is a new publisher and a big supporter of print and play. They have decided to make all of their games available on 18xx-maker as the official print and play provider! If you are able to we highly recommend supporting this publisher by purchasing their excellent production of 1861/67 and the upcoming 1889!

Since Shikoku 1889 has long been released, it should be updated to something like the following.

> [Grand Trunk Games](https://www.grandtrunkgames.com/) is a new publisher and a big supporter of print and play. They have decided to make all of their games available on 18xx-maker as the official print and play provider! If you are able to we highly recommend supporting this publisher by purchasing their excellent productions of 1861/67 and Shikoku 1889!

**Comment by kelsin** [comment]
Thanks! Fixed in next push.
