### ISSUE TITLE
App feature title text displays errors

### ISSUE THREAD

**Issue by waymost** [18xx-maker/18xx-maker#597]
Under the features list, the app-related features display an error instead of the title for each bullet.

> key 'app (en-US)' returned an object instead of string.: Live reloading of games as you edit definition files.
key 'app (en-US)' returned an object instead of string.: Export full games or individual components as PDF documents or PNG images.
key 'app (en-US)' returned an object instead of string.: Export games as Board18 game boxes.

Presumably each of those key return errors should say "App" instead

**Comment by kelsin** [comment]
Fixed in next push. Thanks for finding this!
