### ISSUE TITLE
B18 Map Tiles Offset Incorrectly (Maybe due to orientation horizontal?)

### ISSUE THREAD

**Issue by ngeunit1** [18xx-maker/18xx-maker#97]
It looks like either the vertical offset is off by half a hex, or the horizontal offset is off by about half a hex. I can also provide the game JSON file if necessary. Note that this is the first one I created that was set with orientation horizontal, so not sure if that might be related.

![image](https://user-images.githubusercontent.com/633368/64924481-f5d46a00-d7b2-11e9-9b25-165caefa0199.png)

**Comment by kelsin** [comment]
Shitty, I thought I had this working but haven't looked at that code in a while. I'll take a look at my test cases and try to find time to fix this ASAP. Sorry for the bug.

**Comment by ngeunit1** [comment]
Thanks! Also, not a super urgent issue. Still working on couple of things in parallel, so no rush.

**Comment by Galatolol** [comment]
In my game box, I realised that I have to click on the upper part of a hex in order to correctly choose it.

**Comment by Galatolol** [comment]
I forgot to add, that I have what I described after changing yStart to -50:
  
```
"board": {
    "imgLoc": "images/18IrePL-GAL01/Map.png",
    "xStart": 47,
    "xStep": 87,
    "yStart": -50,
    "yStep": 50
  },
```

This hepls with tiles being off by a half a hex, but results in havingo to click on the upper part of a hex, as I said.

**Comment by kelsin** [comment]
Can everyone recheck on the latest master. Alignment should be better and this should be good on maps that have invalid A1 coords.
